### PR TITLE
I130 Fix issue with older TS compilation

### PR DESCRIPTION
**Pull request by jacobdr**
The node tests are passing, but the karma tests seemed to flake at the end... Lets see how the CI responds

### CODE REVIEW

**Comment by jacobdr** [comment]
Interesting that `npm run test-karma` works, but `yarn run test-karma` fails on my machine

**Comment by dcharbonnier** [comment]
Instead of adding comments maybe we should add a typescript-2.9.d.ts that "correct" the required types and force a compatible implementation.
For the tests we should restaure also the dummy tests that I removed with the implementation.

**Comment by dcharbonnier** [comment]
@jacobdr can you help me with that ? I'm not able to reproduce the issues that this PR is supposed to fix

**Comment by jacobdr** [comment]
@dcharbonnier Here is a repro:
```bash
docker run -it --rm node bash
git clone https://github.com/dcharbonnier/hydrated-ws.git
cd hydrated-ws
yarn global add typescript@3.0.x
tsc --version
yarn
tsc
```

**Comment by dcharbonnier** [comment]
You are not supposed to build the library with a different version of typescript, you are supposed to consume the library (the d.ts essentially) with a different version of typescript.

On version 0.8.1 there was an issue as the [new tests demonstrate ](https://travis-ci.org/dcharbonnier/hydrated-ws/jobs/451097635#L1489)the code has been fixed in 1aa4e166108ec58cece7b6e1092f0ae80a1a284e

This works:
```Dockerfile
FROM node:alpine
RUN apk add --no-cache git
RUN git clone https://github.com/dcharbonnier/hydrated-ws.git \
    && cd hydrated-ws \
    && yarn install \
    && yarn build
```

**Pull request closed without merging**
